version: '3.8'

services:
  backend:
    build: ./basic_search_engine_backend
    ports:
      - "8000:8000"
    volumes:
      - ./basic_search_engine_backend/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./BasicSearchEngine.Web.Blazor
    ports:
      - "5001:80"
    depends_on:
      - backend